# Generated by Django 5.2.7 on 2025-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AylikSaatDengesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donem', models.CharField(max_length=7, verbose_name='Dönem (YYYY-AA)')),
                ('denge', models.FloatField(default=0, verbose_name='Saat Dengesi (+/-)')),
            ],
        ),
        migrations.CreateModel(
            name='CalisanTercihi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')])),
            ],
        ),
        migrations.CreateModel(
            name='KisitlamaKurali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sart', models.CharField(choices=[('cinsiyet_kadin', 'Cinsiyet: Kadın'), ('cinsiyet_erkek', 'Cinsiyet: Erkek')], max_length=50, verbose_name='Kısıtlama Şartı')),
                ('baslangic_saati', models.TimeField(verbose_name='Kısıtlamanın Başladığı Saat (bu saatten sonra)')),
            ],
        ),
        migrations.CreateModel(
            name='Musaitlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')], verbose_name='Haftanın Günü')),
                ('musaitlik_durumu', models.CharField(choices=[('müsait değil', 'Müsait Değil'), ('tüm gün', 'Tüm Gün'), ('11 sonrası', '11:00 Sonrası'), ('14 sonrası', '14:00 Sonrası'), ('17 sonrası', '17:00 Sonrası')], default='müsait değil', max_length=20)),
                ('donem', models.CharField(max_length=7, verbose_name='Dönem (YYYY-AA)')),
            ],
        ),
        migrations.CreateModel(
            name='Vardiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('planlandi', 'Planlandı'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi'), ('taslak', 'Taslak')], default='taslak', max_length=20)),
                ('baslangic_zamani', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('bitis_zamani', models.DateTimeField(verbose_name='Bitiş Zamanı')),
            ],
        ),
        migrations.CreateModel(
            name='VardiyaIstegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istek_tipi', models.CharField(choices=[('takas', 'Takas'), ('iptal', 'İptal')], max_length=10)),
                ('durum', models.CharField(choices=[('hedef_onayi_bekliyor', 'Hedef Onayı Bekliyor'), ('admin_onayi_bekliyor', 'Admin Onayı Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='hedef_onayi_bekliyor', max_length=30)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
