# Generated by Django 5.2.7 on 2025-10-21 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ayliksaatdengesi',
            name='calisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saat_dengeleri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calisantercihi',
            name='calisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tercihleri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calisantercihi',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.sube'),
        ),
        migrations.AddField(
            model_name='kisitlamakurali',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kisitlama_kurallari', to='branches.sube'),
        ),
        migrations.AddField(
            model_name='musaitlik',
            name='calisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musaitlikleri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vardiya',
            name='calisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Çalışan'),
        ),
        migrations.AddField(
            model_name='vardiya',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.sube', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='vardiyaistegi',
            name='hedef_calisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldigi_istekler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vardiyaistegi',
            name='hedef_vardiya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinmak_istenen_istekler', to='schedules.vardiya'),
        ),
        migrations.AddField(
            model_name='vardiyaistegi',
            name='istek_yapan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderdigi_istekler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vardiyaistegi',
            name='istek_yapan_vardiya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklif_edilen_istekler', to='schedules.vardiya'),
        ),
        migrations.AlterUniqueTogether(
            name='ayliksaatdengesi',
            unique_together={('calisan', 'donem')},
        ),
        migrations.AlterUniqueTogether(
            name='musaitlik',
            unique_together={('calisan', 'gun', 'donem')},
        ),
    ]
