# Generated by Django 5.2.7 on 2025-10-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sube_adi', models.CharField(max_length=100, verbose_name='Şube Adı')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('enlem', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Enlem')),
                ('boylam', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Boylam')),
            ],
        ),
        migrations.CreateModel(
            name='SubeCalismaSaati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')], verbose_name='Haftanın Günü')),
                ('acilis_saati', models.TimeField(blank=True, null=True)),
                ('kapanis_saati', models.TimeField(blank=True, null=True)),
                ('kapali', models.BooleanField(default=False, verbose_name='O gün kapalı mı?')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calisma_saatleri', to='branches.sube')),
            ],
            options={
                'unique_together': {('sube', 'gun')},
            },
        ),
    ]
